---
title: "Municipios"
author: "Gisarte"
format: html
editor: source
---

## Municipios

Obtención de límites municipales de España a partir de [MapSpain](https://ropenspain.github.io/mapSpain/)

### Installation


```{r municipios}
library(mapSpain)
library(sf)
library(tidyverse)

library(mapview)

library(reactable)
```

## Seleccionar AOI - Máscara

El área de interés se ha elaborado directamente en QGIS, digitalizando sobre un mapa base.

```{r load-mask}
aoi_mask <- read_sf("../../geoproceso/delivery/aoi_mask.gpkg")

mapview(aoi_mask)
```



## Seleccionar Municipio


```{r aoi_name_20}
aoi_name <- c("Valencia")
```

```{r}
# Get munics
Base <- esp_get_munic(year = "2019", 
                      region = "Valencia")
```

```{r}
reactable(Base,
  searchable = TRUE, striped = TRUE, filterable = TRUE, height = 350#,   elementId = "munis-galicia"
)
```

```{r}
herriak <- c("Massanassa", "Albal", "Paiporta", "Picanya", "Sedaví", "Benetússer", "Beniparrell", "Catarroja","Silla",
"Alfafar")
```


```{r}
# Get munics
aoi <- Base |> 
  filter(name %in% herriak) |> 
  select(c("name", "geometry"))
```

```{r}
plot(aoi)

```



### Guardar aoi

```{r, guardar_aoi-gpkg}
st_write(aoi,
         #paste0("../../proceso/")
         paste0("../../process/geoprocess/",aoi_name, ".gpkg"),
         append = FALSE)

```



